import axios from "axios";
import { GetServerSideProps } from "next";
import Head from "next/head";
import React, { useEffect, useState } from "react";
import styles from "../styles/Home.module.css";
import { Post } from "../types/postTypes";
import { User } from "../types/user";
import { baseURL } from "../types/urls";
import PostCard from "../components/posts/PostCard";

interface HomeProps {
  postsData: Post[];
  user: User;
}

export default function Home({ postsData, user }: HomeProps) {
  const [posts, setPosts] = useState([]);

  useEffect(() => {
    setPosts(postsData);
  }, []);
  //fetch posts and set posts
  const fetchPosts = async () => {
    try {
      const res = await axios.get<Post[]>(`${baseURL}/api/posts`);
      setPosts(res.data);
    } catch (error) {
      console.log(error);
    }
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* render all posts */}
      {posts.map((item) => {
        return (
          <PostCard
            post={item}
            user={user}
            fetchPosts={fetchPosts}
            key={item.id}
          />
        );
      })}
    </div>
  );
}
export const getServerSideProps: GetServerSideProps = async (context) => {
  const { data } = await axios.get<Post[]>(`${baseURL}/api/posts`);

  return {
    props: {
      postsData: data,
    },
  };
};
