import axios from "axios";
import { GetServerSideProps } from "next";
import { AppContext } from "next/app";
import Head from "next/head";
import { useEffect, useState } from "react";
import styles from "../styles/Home.module.css";
import { Post } from "../types/postTypes";
import ThumbUpAltIcon from "@material-ui/icons/ThumbUpAlt";
import ThumbUpOutlinedIcon from "@material-ui/icons/ThumbUpOutlined";
import { IconButton } from "@material-ui/core";

interface HomeProps {
  posts: Post[];
}
export default function Home({ posts }: HomeProps) {
  const [liked, setLiked] = useState(false);
  const [data, setData] = useState([]);
  useEffect(() => {
    setData(posts);
  }, []);
  const likePost = async (postId: string) => {
    const { data } = await axios.post(
      "http://localhost:5000/api/posts/like",
      {
        post_id: postId,
      },
      { withCredentials: true }
    );
    const res = await axios.get<Post[]>("http://localhost:5000/api/posts");
    setData(res.data);
    setLiked(true);
  };
  const unLikePost = async (postId: string) => {
    const { data } = await axios.put(
      "http://localhost:5000/api/posts/like",
      {
        post_id: postId,
      },
      { withCredentials: true }
    );
    const res = await axios.get<Post[]>("http://localhost:5000/api/posts");
    setData(res.data);
    setLiked(false);
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {data.map((item) => {
        return (
          <div className="card mt-3" style={{ width: "550px" }} key={item.id}>
            <img
              className="card-img-top"
              src={`http://localhost:5000/${item.image}`}
              alt={item.title}
            />
            <div className="card-body">
              <h5 className="card-title">{item.title}</h5>
              <p className="card-text">{item.description}</p>
            </div>
            <ul className="list-group list-group-flush">
              <li className="list-group-item">{item.name}</li>
              <li className="list-group-item">{item.created_at}</li>
              <li className="list-group-item">
                <strong>Likes: </strong>
                {item.likes}
              </li>
              <li className="list-group-item">
                {liked ? (
                  <IconButton
                    onClick={(
                      event: React.MouseEvent<HTMLButtonElement, MouseEvent>
                    ) => unLikePost(item.id)}
                  >
                    <ThumbUpAltIcon color="primary" />
                  </IconButton>
                ) : (
                  <IconButton
                    onClick={(
                      event: React.MouseEvent<HTMLButtonElement, MouseEvent>
                    ) => likePost(item.id)}
                  >
                    <ThumbUpAltIcon />
                  </IconButton>
                )}
              </li>
            </ul>
          </div>
        );
      })}
    </div>
  );
}
export const getServerSideProps: GetServerSideProps = async (context) => {
  const { data } = await axios.get<Post[]>("http://localhost:5000/api/posts");
  return {
    props: {
      posts: data,
    },
  };
};
