import axios from "axios";
import { GetServerSideProps } from "next";
import { AppContext } from "next/app";
import Head from "next/head";
import { useState } from "react";
import styles from "../styles/Home.module.css";
import { Post } from "../types/postTypes";

interface HomeProps {
  posts: Post[];
}

export default function Home({ posts }: HomeProps) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {posts.map((item) => {
        return (
          <div className="card mt-3" style={{ width: "400px" }} key={item.id}>
            <img
              className="card-img-top"
              src={`http://localhost:5000/${item.image}`}
              alt={item.title}
            />
            <div className="card-body">
              <h5 className="card-title">{item.title}</h5>
              <p className="card-text">{item.description}</p>
            </div>
            <ul className="list-group list-group-flush">
              <li className="list-group-item">{item.name}</li>
              <li className="list-group-item">{item.created_at}</li>
            </ul>
            <div className="card-body">
              <a href="#" className="card-link">
                <strong>Likes: </strong>
                {item.likes}
              </a>
              <a href="#" className="card-link">
                <strong>Comments: </strong>
                {item.comments}
              </a>
            </div>
          </div>
          // <div key={item.id}>
          //   <div>
          //     <strong>ID: </strong>
          //     {item.id}
          //   </div>
          //   <div>
          //     <strong>Post Title: </strong>
          //     {item.description}
          //   </div>
          //   <div>
          //     <strong>Post Description: </strong>
          //     {item.description}
          //   </div>
          //   <div>
          //     <strong>Post Image: </strong>
          //     {item.image}
          //   </div>
          //   <div>
          //     <strong>User Name: </strong>
          //     {item.name}
          //   </div>
          //   <div>
          //     <strong>Likes: </strong>
          //     {item.likes}
          //   </div>
          //   <br />
          //   <br />
          // </div>
        );
      })}
    </div>
  );
}
export const getServerSideProps: GetServerSideProps = async (context) => {
  const { data } = await axios.get<Post[]>("http://localhost:5000/api/posts");
  return {
    props: {
      posts: data,
    },
  };
};
